name: Deploy Blog

on: [push] # 当有新push时运行

jobs:
  build: # 一项叫做build的任务

    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    
    steps:
    - name: Checkout # 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@v1 # 脚本来自 https://github.com/actions/checkout
      
    - name: Use Node.js 13.x # 配置Node环境
      uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
      with:
        node-version: "13.x"
    - name: Setup Hexo env
      run: |
        # install dependencies
        npm i -g hexo-cli # 安装hexo
        npm i
        hexo clean
        hexo generate  
    - name: Deploy
      env:
        GH_REF: git@github.com:davidnotes/davidnotes.github.io.git
        ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY }}
      run: |
        # publish
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        # set git infomation
        git config --global user.name 'davidnotes' 
        git config --global user.email 'gujinxin.dell@gmail.com'
        git clone ${GH_REF} hexo-public
        cp -rf public/* hexo-public/ 
        cd hexo-public
        git add .
        git commit -am "Deployed by GitHub Actions ..."
        git push origin master
